### ISSUE TITLE
1.20.4 Update?

### ISSUE THREAD

**Issue by SirPotato42** [teddyxlandlee/f3sconfirm#1]
As the title says, a 1.20.4 version of this mod would be nice

**Comment by teddyxlandlee** [comment]
I'm sorry to tell you that I'm too busy IRL to test mod compatibility. I'll appreciate it if you could help me test whether the mod can actually run on 1.20.4.

Thank you!

**Comment by maskersss** [comment]
works fine for me on 1.20.4 and 1.20.6, crashes on 1.21 though: https://mclo.gs/R62oMCB

**Comment by teddyxlandlee** [comment]
> works fine for me on 1.20.4 and 1.20.6, crashes on 1.21 though: https://mclo.gs/R62oMCB

1.20.4 has already been compatible

Since version [1.0.2](https://modrinth.com/mod/f3sconfirm/version/1.0.2) is released, 1.21+ is supported now.
